# Generated by Django 6.0 on 2026-01-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestuser',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
