# Generated by Django 6.0 on 2026-01-12 05:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PLACEHOLDER', 'Placeholder'), ('ACTIVE', 'Active'), ('HIDDEN', 'Hidden'), ('PAUSED', 'Paused'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('user', 'User'), ('guest', 'Guest')], default='user', max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('traveler_details', models.JSONField(default=[])),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('booked_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_tour_plans', to='core.guestuser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tour_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('available_adults', models.PositiveIntegerField()),
                ('available_children', models.PositiveIntegerField()),
                ('available_infants', models.PositiveIntegerField()),
                ('available_youth', models.PositiveIntegerField(default=0)),
                ('available_student_eu', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='tour_plan.tourdate')),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('tour_date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='TourPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('max_adults', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_adult', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adult_age_min', models.PositiveIntegerField(default=18)),
                ('adult_age_max', models.PositiveIntegerField(default=99)),
                ('max_children', models.PositiveIntegerField(default=0)),
                ('price_child', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('child_age_min', models.PositiveIntegerField(default=3)),
                ('child_age_max', models.PositiveIntegerField(default=17)),
                ('max_infants', models.PositiveIntegerField(default=0)),
                ('price_infant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('infant_age_min', models.PositiveIntegerField(default=0)),
                ('infant_age_max', models.PositiveIntegerField(default=2)),
                ('max_youth', models.PositiveIntegerField(default=0)),
                ('price_youth', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('youth_age_min', models.PositiveIntegerField(default=18)),
                ('youth_age_max', models.PositiveIntegerField(default=25)),
                ('max_student_eu', models.PositiveIntegerField(default=0)),
                ('price_student_eu', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('student_eu_age_min', models.PositiveIntegerField(default=18)),
                ('student_eu_age_max', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PLACEHOLDER', 'Placeholder'), ('ACTIVE', 'Active'), ('HIDDEN', 'Hidden'), ('PAUSED', 'Paused'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('images', models.ManyToManyField(blank=True, related_name='images_tour', to='tour_plan.image')),
                ('locations', models.ManyToManyField(blank=True, related_name='tour_plans', to='tour_plan.location')),
            ],
        ),
        migrations.AddField(
            model_name='tourdate',
            name='tour_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_dates', to='tour_plan.tourplan'),
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_adults', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('num_children', models.PositiveIntegerField(default=0)),
                ('num_infants', models.PositiveIntegerField(default=0)),
                ('num_youth', models.PositiveIntegerField(default=0)),
                ('num_student_eu', models.PositiveIntegerField(default=0)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_items', to='tour_plan.booking')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_items', to='tour_plan.timeslot')),
                ('tour_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_items', to='tour_plan.tourplan')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tourdate',
            unique_together={('tour_plan', 'date')},
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_adults', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('num_children', models.PositiveIntegerField(default=0)),
                ('num_infants', models.PositiveIntegerField(default=0)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_youth', models.PositiveIntegerField(default=0)),
                ('num_student_eu', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='tour_plan.timeslot')),
                ('tour_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='tour_plan.tourplan')),
            ],
            options={
                'unique_together': {('user', 'tour_plan', 'time_slot')},
            },
        ),
    ]
