# Generated by Django 6.0 on 2026-01-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='tour_plan'),
        ),
    ]
