# Generated by Django 6.0 on 2026-01-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_plan', '0002_alter_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourplan',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='excludes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='free_cancellation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='highlights',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='includes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='know_before_you_go',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='not_allowed',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='not_suitable_for',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='pickup_included',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
