# Generated by Django 6.0 on 2026-01-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_plan', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='open', max_length=20),
        ),
    ]
