# Generated by Django 6.0 on 2026-01-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_plan', '0006_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
