# Generated by Django 6.0 on 2026-02-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_plan', '0009_alter_timeslot_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
