# Generated by Django 6.0 on 2026-02-19 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_plan', '0010_alter_notice_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourplan',
            name='max_adults',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='price_adult',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
